# Generated by Django 5.2.4 on 2025-09-03 02:18

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_category_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_image',
            field=models.ImageField(default='', upload_to=job.models.image_upload),
            preserve_default=False,
        ),
    ]
