# Generated by Django 5.2.4 on 2025-09-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.CharField(choices=[('A', 'Cairo'), ('B', 'Alexandria'), ('C', ' Giza'), ('D', 'Luxor'), ('E', 'Aswan'), ('F', 'Port Said'), ('G', 'Suez')], default=''),
            preserve_default=False,
        ),
    ]
