# Generated by Django 5.2.4 on 2025-09-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_location',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('A', 'Cairo'), ('Alexandria', 'Alexandria'), ('Giza', ' Giza'), ('Luxor', 'Luxor'), ('Aswan', 'Aswan'), ('Port Said', 'Port Said'), ('Suez', 'Suez')], default=''),
            preserve_default=False,
        ),
    ]
