# Generated by Django 5.2.4 on 2025-09-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='apply/')),
                ('coverletter', models.TextField(max_length=500)),
            ],
        ),
    ]
