# Generated by Django 5.2.4 on 2025-09-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_applyer_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
