# Generated by Django 5.2.4 on 2025-09-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_applyer_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyer',
            old_name='coverletter',
            new_name='cover_letter',
        ),
    ]
